# Generated by Django 3.2.5 on 2021-07-10 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dispenser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'verbose_name': 'IP address',
                     'verbose_name_plural': 'IP addresses'},
        ),
        migrations.AlterModelOptions(
            name='ipsubnet',
            options={'verbose_name': 'IP subnet',
                     'verbose_name_plural': 'IP subnets'},
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='claimed_at',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата выдачи'),
            preserve_default=False,
        ),
    ]
