# Generated by Django 3.2.5 on 2021-07-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispenser', '0002_auto_20210710_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'verbose_name': 'IP-адрес',
                     'verbose_name_plural': 'IP-адреса'},
        ),
        migrations.AlterModelOptions(
            name='ipsubnet',
            options={'ordering': [
                'address'], 'verbose_name': 'Подсеть IP', 'verbose_name_plural': 'Подсети IP'},
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='claimed_at',
            field=models.DateTimeField(
                auto_now=True, verbose_name='дата выдачи'),
        ),
    ]
