# Generated by Django 3.2.5 on 2021-07-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispenser', '0003_auto_20210711_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='address',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name='ipsubnet',
            name='address',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
