# Generated by Django 3.2.5 on 2021-07-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispenser', '0004_auto_20210711_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipsubnet',
            name='protocol',
            field=models.CharField(
                choices=[('v4', 'IPv4'), ('v6', 'IPv6')], default='v4', max_length=2),
            preserve_default=False,
        ),
    ]
