# Generated by Django 3.2.5 on 2021-07-12 18:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dispenser', '0005_ipsubnet_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='address',
            field=models.GenericIPAddressField(
                unique=True, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='ip_addresses', to=settings.AUTH_USER_MODEL, verbose_name='владелец'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='subnet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='addresses', to='dispenser.ipsubnet', verbose_name='подсеть'),
        ),
        migrations.AlterField(
            model_name='ipsubnet',
            name='address',
            field=models.GenericIPAddressField(
                unique=True, verbose_name='адрес подсети'),
        ),
        migrations.AlterField(
            model_name='ipsubnet',
            name='gateway',
            field=models.GenericIPAddressField(
                default='255.255.255.255', verbose_name='адрес шлюза'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ipsubnet',
            name='mask',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(
                0), django.core.validators.MaxValueValidator(128)], verbose_name='маска подсети'),
        ),
        migrations.AlterField(
            model_name='ipsubnet',
            name='protocol',
            field=models.CharField(
                choices=[('v4', 'IPv4'), ('v6', 'IPv6')], max_length=2, verbose_name='протокол'),
        ),
    ]
